### ISSUE TITLE
Screen tearing workaround

### ISSUE THREAD

**Issue by szymor** [zear/shisen-seki#1]
On some platforms, e.g. Bittboy, frequent display refreshing causes visual artifacts to appear. As the game does not involve animations, would it be possible to redraw screen only on certain events, e.g. user input or timer tick? It would make easier to port the game for such platforms and would lower CPU and battery usage.

**Comment by zear** [comment]
In SDL 1.2, the internal framebuffer is not supposed to refresh until a call to SDL_Flip (for hardware surfaces) or SDL_UpdateRect (for software surfaces), which in Shisen-Seki (and my other games) happens only after all the rendering for the given frame has been completed. If your platform updates the screen mid-frame, it implies its SDL backend must be broken. Please make sure the screen surface has been initialized with SDL_SWSURFACE if you are not using double buffering.

Regardless of that, I agree with you that there is no need for Shisen-Seki to run at a fixed framerate, so I made experimental changes to decouple gameplay from framerate. You can find them in "adaptive_framerate" branch. Let me know if it improves performance for you.

**Comment by szymor** [comment]
Menu seems to be working fine. Game screen is like before, the behaviour is dependent on cursor position. For most of them, the screen tears as always. For a few of them it seems to be fine. I would not consider this fix a definite solution to the problem.

**Comment by szymor** [comment]
Speaking of SDL_SWSURFACE, turning it on solves the problem. The game timer gets slower but at the moment I do not consider it a major issue. Thanks for help :)

**Comment by zear** [comment]
Is the game timer accurate now, or is it running slower than a real clock?
If it's the latter and you also run the game without -DADAPTIVE_FRAMERATE, that would suggest your hardware is too slow to render 60 frames per second.

**Comment by szymor** [comment]
1) When adaptive framerate is on, SetVideoMode() flags are SDL_HWSURFACE and SDL_DOUBLEBUF, I believe the timer is fine. I am not sure, because I did not pay attention to it, but I think I would notice that something is wrong.
2) When adaptive framerate is off and SetVideoMode() flag is SDL_SWSURFACE, the display is fine but the timer is running slower than a real clock.

I did not test adaptive framerate with swsurface on, but I believe it could cause timing fluctuations caused by the behaviour described earlier. For your information, Bittboy runs many games and emulators, many of them works at 60 fps. I had similar issue with your other game (Homing Fever) and I believe it is caused by inaccuracy of framerate limiter (it needs to be enabled for Bittboy).

**Comment by szymor** [comment]
> I had similar issue with your other game (Homing Fever) and I believe it is caused by inaccuracy of framerate limiter (it needs to be enabled for Bittboy).

It seems to be some kind of a bug on Bittboy itself. Usually it is enough to restart the program or game to run it at normal speed.
I think I can close the issue as SDL_SWSURFACE solves my problem.
